// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (
  id,
  title,
  description,
  location,
  accept_responses_until,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, location, accept_responses_until, created_at, updated_at
`

type CreateCalendarParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Location             pgtype.Text        `json:"location"`
	AcceptResponsesUntil pgtype.Timestamptz `json:"accept_responses_until"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.AcceptResponsesUntil,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.AcceptResponsesUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarByID = `-- name: DeleteCalendarByID :exec
DELETE FROM calendars
WHERE id = $1
`

func (q *Queries) DeleteCalendarByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendarByID, id)
	return err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT id, title, description, location, accept_responses_until, created_at, updated_at
FROM calendars
WHERE id = $1
`

func (q *Queries) GetCalendarByID(ctx context.Context, id pgtype.UUID) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.AcceptResponsesUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
