// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_time_slots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarTimeSlot = `-- name: CreateCalendarTimeSlot :one
INSERT INTO calendar_time_slots (
  calendar_id,
  start_date,
  end_date
)
VALUES ($1, $2, $3)
RETURNING id, calendar_id, start_date, end_date, created_at, updated_at
`

type CreateCalendarTimeSlotParams struct {
	CalendarID pgtype.UUID        `json:"calendar_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) CreateCalendarTimeSlot(ctx context.Context, arg CreateCalendarTimeSlotParams) (CalendarTimeSlot, error) {
	row := q.db.QueryRow(ctx, createCalendarTimeSlot, arg.CalendarID, arg.StartDate, arg.EndDate)
	var i CalendarTimeSlot
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarTimeSlotByID = `-- name: DeleteCalendarTimeSlotByID :exec
DELETE FROM calendar_time_slots
WHERE id = $1
`

func (q *Queries) DeleteCalendarTimeSlotByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendarTimeSlotByID, id)
	return err
}

const getCalendarTimeSlotsByCalendarID = `-- name: GetCalendarTimeSlotsByCalendarID :many
SELECT 
  id,
  calendar_id,
  start_date,
  end_date,
  created_at,
  updated_at
FROM calendar_time_slots
WHERE calendar_id = $1
ORDER BY start_date, end_date
`

func (q *Queries) GetCalendarTimeSlotsByCalendarID(ctx context.Context, calendarID pgtype.UUID) ([]CalendarTimeSlot, error) {
	rows, err := q.db.Query(ctx, getCalendarTimeSlotsByCalendarID, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarTimeSlot{}
	for rows.Next() {
		var i CalendarTimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
