// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (
  title,
  description,
  location,
  accept_responses_until,
  password
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateCalendarParams struct {
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	Location             *string            `json:"location"`
	AcceptResponsesUntil pgtype.Timestamptz `json:"accept_responses_until"`
	Password             *string            `json:"password"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.AcceptResponsesUntil,
		arg.Password,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCalendarByID = `-- name: DeleteCalendarByID :exec
DELETE FROM calendars
WHERE id = $1
`

func (q *Queries) DeleteCalendarByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendarByID, id)
	return err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT id, title, description, location, accept_responses_until, password, created_at, updated_at
FROM calendars
WHERE id = $1
`

func (q *Queries) GetCalendarByID(ctx context.Context, id pgtype.UUID) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.AcceptResponsesUntil,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
