// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_time_slots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarTimeSlot = `-- name: CreateCalendarTimeSlot :one
INSERT INTO calendar_time_slots (
  id,
  calendar_id,
  slot_date,
  start_time,
  end_time,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, calendar_id, slot_date, start_time, end_time, created_at, updated_at
`

type CreateCalendarTimeSlotParams struct {
	ID         pgtype.UUID        `json:"id"`
	CalendarID pgtype.UUID        `json:"calendar_id"`
	SlotDate   pgtype.Date        `json:"slot_date"`
	StartTime  pgtype.Time        `json:"start_time"`
	EndTime    pgtype.Time        `json:"end_time"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCalendarTimeSlot(ctx context.Context, arg CreateCalendarTimeSlotParams) (CalendarTimeSlot, error) {
	row := q.db.QueryRow(ctx, createCalendarTimeSlot,
		arg.ID,
		arg.CalendarID,
		arg.SlotDate,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CalendarTimeSlot
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.SlotDate,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarTimeSlotByID = `-- name: DeleteCalendarTimeSlotByID :exec
DELETE FROM calendar_time_slots
WHERE id = $1
`

func (q *Queries) DeleteCalendarTimeSlotByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendarTimeSlotByID, id)
	return err
}

const getCalendarTimeSlotsByCalendarID = `-- name: GetCalendarTimeSlotsByCalendarID :many
SELECT 
  id,
  calendar_id,
  slot_date,
  start_time,
  end_time,
  created_at,
  updated_at
FROM calendar_time_slots
WHERE calendar_id = $1
ORDER BY slot_date, start_time
`

func (q *Queries) GetCalendarTimeSlotsByCalendarID(ctx context.Context, calendarID pgtype.UUID) ([]CalendarTimeSlot, error) {
	rows, err := q.db.Query(ctx, getCalendarTimeSlotsByCalendarID, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarTimeSlot
	for rows.Next() {
		var i CalendarTimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.SlotDate,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
