// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ID                   pgtype.UUID
	Title                string
	Description          pgtype.Text
	Location             pgtype.Text
	AcceptResponsesUntil pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type CalendarTimeSlot struct {
	ID         pgtype.UUID
	CalendarID pgtype.UUID
	SlotDate   pgtype.Date
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Vote struct {
	ID                 pgtype.UUID
	CalendarID         pgtype.UUID
	CalendarTimeSlotID pgtype.UUID
	Username           string
	Available          []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
