// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ID                   pgtype.UUID        `json:"id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Location             pgtype.Text        `json:"location"`
	AcceptResponsesUntil pgtype.Timestamptz `json:"accept_responses_until"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type CalendarTimeSlot struct {
	ID         pgtype.UUID        `json:"id"`
	CalendarID pgtype.UUID        `json:"calendar_id"`
	SlotDate   pgtype.Date        `json:"slot_date"`
	StartTime  pgtype.Time        `json:"start_time"`
	EndTime    pgtype.Time        `json:"end_time"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Vote struct {
	ID                 pgtype.UUID        `json:"id"`
	CalendarID         pgtype.UUID        `json:"calendar_id"`
	CalendarTimeSlotID pgtype.UUID        `json:"calendar_time_slot_id"`
	Username           string             `json:"username"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
