// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ID                   pgtype.UUID        `json:"id"`
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	Location             *string            `json:"location"`
	AcceptResponsesUntil pgtype.Timestamptz `json:"accept_responses_until"`
	Password             *string            `json:"password"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type CalendarTimeSlot struct {
	ID         pgtype.UUID        `json:"id"`
	CalendarID pgtype.UUID        `json:"calendar_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Vote struct {
	ID                 pgtype.UUID        `json:"id"`
	CalendarID         pgtype.UUID        `json:"calendar_id"`
	CalendarTimeSlotID pgtype.UUID        `json:"calendar_time_slot_id"`
	Username           string             `json:"username"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
